#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

nginx_status=$(service nginx status)
if [[ "$nginx_status" == *"not running"* ]]; then
    sed -i 's/#.*listen 80;/listen 80;/g' /etc/nginx/nginx.conf
    service nginx restart
fi
